### ISSUE TITLE
rarbg - not showing file size and cant catch the smaller versions (non 720 or 1080)

### ISSUE THREAD

**Issue by ibox99** [mancuniancol/script.quasar.rarbg-mc#3]
hello,

the provider isn't showing the file sizes in the window to choose the stream/version we want.

also, dont know if it is a bug but sometimes i try to search for the smaller versions of a film and the provider cant find it (and it is online).
example: xxxxxxxx.2016.BDRip.x264-GECKOS

only catch these types:
2016.720p.BRRip.XviD.AC3-RARBG
2016.720p.BluRay.H264.AAC-RARBG
2016.1080p.BluRay.H264.AAC-RARBG

also i think the other providers (for quasar) dont search the smaller files

thank you

**Comment by mancuniancol** [comment]
This provider uses rarbg API. For that reason, it doesn't behaviour like the other provide. For example, It doesn't support size information. 
It is nothing I can't do. Sorry.
